# Generated by Django 3.1.3 on 2020-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ins_id', models.CharField(max_length=4)),
                ('Ins_name', models.CharField(max_length=50)),
            ],
        ),
    ]
