# Generated by Django 3.1.3 on 2020-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ins_id', models.CharField(max_length=4)),
                ('Ins_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.CharField(max_length=5)),
                ('r_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sj_id', models.CharField(max_length=6)),
                ('sj_name', models.CharField(max_length=50)),
                ('sj_classes', models.IntegerField()),
                ('sj_ins', models.ManyToManyField(to='Schedule.Instructors')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=15)),
            ],
            options={
                'unique_together': {('time', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('subjects', models.ManyToManyField(to='Schedule.Subject')),
            ],
        ),
    ]
