# Generated by Django 3.1.3 on 2020-11-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='r_number',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sj_id', models.CharField(max_length=6)),
                ('sj_name', models.CharField(max_length=50)),
                ('sj_classes', models.IntegerField()),
                ('sj_ins', models.ManyToManyField(to='Schedule.Instructors')),
            ],
        ),
    ]
