# Generated by Django 3.1.3 on 2020-11-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_auto_20201110_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='shift',
            new_name='r_name',
        ),
    ]
