# Generated by Django 3.1.3 on 2020-11-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_auto_20201111_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='r_name',
            field=models.CharField(max_length=5),
        ),
    ]
