# Generated by Django 3.1.3 on 2020-11-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
