# Generated by Django 3.1.3 on 2020-11-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0007_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sj_ins',
            field=models.ManyToManyField(null=True, to='Schedule.Instructors'),
        ),
    ]
