# Generated by Django 3.1.3 on 2020-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0008_auto_20201117_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sj_ins',
            field=models.ManyToManyField(to='Schedule.Instructors'),
        ),
    ]
