# Generated by Django 3.1.3 on 2020-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0009_auto_20201117_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('sid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('time', models.CharField(choices=[('Shift 1', '6:50 - 9:15'), ('Shift 2', '9:25 - 11:50'), ('Shift 3', '12:30 - 14:55'), ('Shift 4', '15:05 - 17:30'), ('Shift 5', '17:45 - 21:00')], default='6:50 - 9:15', max_length=50)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
            ],
        ),
    ]
